CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  company text NULL,
  message text NOT NULL,
  privacy_accepted boolean NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.contact_submissions FROM anon, authenticated;
GRANT ALL ON TABLE public.contact_submissions TO service_role;
REVOKE ALL ON SEQUENCE public.contact_submissions_id_seq FROM anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.contact_submissions_id_seq TO service_role;

COMMENT ON TABLE public.contact_submissions IS
  'The table is accessed through server-side code using the Supabase service role. No anonymous public policies are intentionally defined.';
